// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  job_board: dynamic(() => import("./JobBoard")),
  opportunities_list: dynamic(() => import("./OpportunitiesList")),
  opportunities_section: dynamic(() => import("./OpportunitiesSection")),
};
