// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ListeDocumentDataSlicesSlice = JobBoardSlice;

/**
 * Content for liste documents
 */
interface ListeDocumentData {
  /**
   * Slice Zone field in *liste*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ListeDocumentDataSlicesSlice>; /**
   * Meta Title field in *liste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: liste.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *liste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: liste.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *liste*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * liste document from Prismic
 *
 * - **API ID**: `liste`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ListeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ListeDocumentData>, "liste", Lang>;

type MentionDocumentDataSlicesSlice = LegalTermsSlice;

/**
 * Content for mention documents
 */
interface MentionDocumentData {
  /**
   * Slice Zone field in *mention*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mention.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MentionDocumentDataSlicesSlice>; /**
   * Meta Title field in *mention*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mention.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *mention*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mention.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *mention*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mention.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * mention document from Prismic
 *
 * - **API ID**: `mention`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionDocumentData>,
    "mention",
    Lang
  >;

type ProfilDocumentDataSlicesSlice = JobListingsSlice;

/**
 * Content for profil documents
 */
interface ProfilDocumentData {
  /**
   * Slice Zone field in *profil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProfilDocumentDataSlicesSlice>; /**
   * Meta Title field in *profil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: profil.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *profil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: profil.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *profil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profil.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * profil document from Prismic
 *
 * - **API ID**: `profil`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ProfilDocumentData>, "profil", Lang>;

type SingleDocumentDataSlicesSlice = JobPostingSlice;

/**
 * Content for single documents
 */
interface SingleDocumentData {
  /**
   * Slice Zone field in *single*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: single.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SingleDocumentDataSlicesSlice>; /**
   * Meta Title field in *single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: single.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *single*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: single.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *single*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * single document from Prismic
 *
 * - **API ID**: `single`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SingleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SingleDocumentData>, "single", Lang>;

type TagDocumentDataSlicesSlice = OpportunitiesListSlice;

/**
 * Content for tag documents
 */
interface TagDocumentData {
  /**
   * Slice Zone field in *tag*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TagDocumentDataSlicesSlice>; /**
   * Meta Title field in *tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tag.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tag.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *tag*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TagDocumentData>, "tag", Lang>;

export type AllDocumentTypes =
  | HomeDocument
  | ListeDocument
  | MentionDocument
  | ProfilDocument
  | SingleDocument
  | TagDocument;

/**
 * Item in *JobBoard → Default → Primary → Job Cards*
 */
export interface JobBoardSliceDefaultPrimaryJobCardsItem {
  /**
   * Job Title field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_title: prismic.RichTextField;

  /**
   * Job Reference field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_reference
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_reference: prismic.KeyTextField;

  /**
   * Technologies field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  technologies: prismic.RichTextField;

  /**
   * Job Description field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_description: prismic.RichTextField;
}

/**
 * Primary content in *JobBoard → Default → Primary*
 */
export interface JobBoardSliceDefaultPrimary {
  /**
   * Title field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Filter Buttons field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.filter_buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  filter_buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Job Cards field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  job_cards: prismic.GroupField<
    Simplify<JobBoardSliceDefaultPrimaryJobCardsItem>
  >;
}

/**
 * Default variation for JobBoard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with job listings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobBoardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobBoardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobBoard*
 */
type JobBoardSliceVariation = JobBoardSliceDefault;

/**
 * JobBoard Shared Slice
 *
 * - **API ID**: `job_board`
 * - **Description**: A job listings section with title, filter buttons, and a grid of job cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobBoardSlice = prismic.SharedSlice<
  "job_board",
  JobBoardSliceVariation
>;

/**
 * Item in *JobDetail → Default → Primary → Technologies*
 */
export interface JobDetailSliceDefaultPrimaryTechnologiesItem {
  /**
   * Technology Name field in *JobDetail → Default → Primary → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.technologies[].tech
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tech: prismic.KeyTextField;
}

/**
 * Primary content in *JobDetail → Default → Primary*
 */
export interface JobDetailSliceDefaultPrimary {
  /**
   * CTA Label field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., < Voir toutes les offres
   * - **API ID Path**: job_detail.default.primary.ctaLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ctaLabel: prismic.KeyTextField;

  /**
   * CTA Link field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.ctaLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Job Title field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Post Date field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.postDate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  postDate: prismic.DateField;

  /**
   * Technologies field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.technologies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<JobDetailSliceDefaultPrimaryTechnologiesItem>
  >;

  /**
   * Job Description field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_detail.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Application Textarea Placeholder field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Postuler à cette offre ...
   * - **API ID Path**: job_detail.default.primary.applicationLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  applicationLabel: prismic.KeyTextField;

  /**
   * Submit Button Label field in *JobDetail → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Envoyer
   * - **API ID Path**: job_detail.default.primary.submitButtonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submitButtonLabel: prismic.KeyTextField;
}

/**
 * Default variation for JobDetail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default job detail variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobDetailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobDetailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobDetail*
 */
type JobDetailSliceVariation = JobDetailSliceDefault;

/**
 * JobDetail Shared Slice
 *
 * - **API ID**: `job_detail`
 * - **Description**: Job posting detail with title, date, technologies, description, and application form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobDetailSlice = prismic.SharedSlice<
  "job_detail",
  JobDetailSliceVariation
>;

/**
 * Item in *JobListings → Default → Primary → Job Offerings*
 */
export interface JobListingsSliceDefaultPrimaryOfferingsItemsItem {
  /**
   * Job Title field in *JobListings → Default → Primary → Job Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_items[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_title: prismic.KeyTextField;

  /**
   * Job ID field in *JobListings → Default → Primary → Job Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_items[].job_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_id: prismic.KeyTextField;

  /**
   * Technologies field in *JobListings → Default → Primary → Job Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_items[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Description field in *JobListings → Default → Primary → Job Offerings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *JobListings → Default → Primary → Application History*
 */
export interface JobListingsSliceDefaultPrimaryHistoryItemsItem {
  /**
   * Job ID field in *JobListings → Default → Primary → Application History*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_items[].job_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_id: prismic.KeyTextField;

  /**
   * Job Title field in *JobListings → Default → Primary → Application History*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_items[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_title: prismic.KeyTextField;

  /**
   * Technologies field in *JobListings → Default → Primary → Application History*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_items[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Description field in *JobListings → Default → Primary → Application History*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *JobListings → Default → Primary*
 */
export interface JobListingsSliceDefaultPrimary {
  /**
   * Offerings Section Title field in *JobListings → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  offerings_title: prismic.RichTextField;

  /**
   * Job Offerings field in *JobListings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.offerings_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  offerings_items: prismic.GroupField<
    Simplify<JobListingsSliceDefaultPrimaryOfferingsItemsItem>
  >;

  /**
   * History Section Title field in *JobListings → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  history_title: prismic.RichTextField;

  /**
   * Application History field in *JobListings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_listings.default.primary.history_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  history_items: prismic.GroupField<
    Simplify<JobListingsSliceDefaultPrimaryHistoryItemsItem>
  >;
}

/**
 * Default variation for JobListings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobListingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobListingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobListings*
 */
type JobListingsSliceVariation = JobListingsSliceDefault;

/**
 * JobListings Shared Slice
 *
 * - **API ID**: `job_listings`
 * - **Description**: A slice displaying job offerings and application history
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobListingsSlice = prismic.SharedSlice<
  "job_listings",
  JobListingsSliceVariation
>;

/**
 * Item in *JobPosting → Default → Primary → Technologies*
 */
export interface JobPostingSliceDefaultPrimaryTechnologiesItem {
  /**
   * Technology Name field in *JobPosting → Default → Primary → Technologies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_posting.default.primary.technologies[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *JobPosting → Default → Primary*
 */
export interface JobPostingSliceDefaultPrimary {
  /**
   * Title field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_posting.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Date field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job_posting.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Technologies field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_posting.default.primary.technologies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  technologies: prismic.GroupField<
    Simplify<JobPostingSliceDefaultPrimaryTechnologiesItem>
  >;

  /**
   * Description field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_posting.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Application Text field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Postuler à cette offre ...
   * - **API ID Path**: job_posting.default.primary.applicationText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  applicationText: prismic.RichTextField;

  /**
   * Submit Button Text field in *JobPosting → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Envoyer
   * - **API ID Path**: job_posting.default.primary.submitButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submitButtonText: prismic.KeyTextField;
}

/**
 * Default variation for JobPosting Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default job posting variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobPostingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobPostingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobPosting*
 */
type JobPostingSliceVariation = JobPostingSliceDefault;

/**
 * JobPosting Shared Slice
 *
 * - **API ID**: `job_posting`
 * - **Description**: Job posting slice with title, date, technologies, description, and application form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobPostingSlice = prismic.SharedSlice<
  "job_posting",
  JobPostingSliceVariation
>;

/**
 * Item in *LegalTerms → Default → Primary → Sections*
 */
export interface LegalTermsSliceDefaultPrimarySectionsItem {
  /**
   * Section Title field in *LegalTerms → Default → Primary → Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter section title
   * - **API ID Path**: legal_terms.default.primary.sections[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Content field in *LegalTerms → Default → Primary → Sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter section content
   * - **API ID Path**: legal_terms.default.primary.sections[].section_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_content: prismic.RichTextField;
}

/**
 * Primary content in *LegalTerms → Default → Primary*
 */
export interface LegalTermsSliceDefaultPrimary {
  /**
   * Heading field in *LegalTerms → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter page heading
   * - **API ID Path**: legal_terms.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Sections field in *LegalTerms → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_terms.default.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sections: prismic.GroupField<
    Simplify<LegalTermsSliceDefaultPrimarySectionsItem>
  >;
}

/**
 * Default variation for LegalTerms Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation for legal terms
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegalTermsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalTermsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalTerms*
 */
type LegalTermsSliceVariation = LegalTermsSliceDefault;

/**
 * LegalTerms Shared Slice
 *
 * - **API ID**: `legal_terms`
 * - **Description**: A slice for displaying legal terms and mentions légales content with sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegalTermsSlice = prismic.SharedSlice<
  "legal_terms",
  LegalTermsSliceVariation
>;

/**
 * Item in *OpportunitiesList → Default → Primary → Opportunities*
 */
export interface OpportunitiesListSliceDefaultPrimaryOpportunitiesItem {
  /**
   * Job Title field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].jobTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  jobTitle: prismic.RichTextField;

  /**
   * Posting Date field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].postingDate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  postingDate: prismic.DateField;

  /**
   * Technologies field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Techno1, Techno2, Techno3
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Description field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *OpportunitiesList → Default → Primary*
 */
export interface OpportunitiesListSliceDefaultPrimary {
  /**
   * Heading field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Techno 1
   * - **API ID Path**: opportunities_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Opportunity Count field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunityCount
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  opportunityCount: prismic.NumberField;

  /**
   * View All Link field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.viewAllLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  viewAllLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Opportunities field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  opportunities: prismic.GroupField<
    Simplify<OpportunitiesListSliceDefaultPrimaryOpportunitiesItem>
  >;
}

/**
 * Default variation for OpportunitiesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunitiesListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OpportunitiesList*
 */
type OpportunitiesListSliceVariation = OpportunitiesListSliceDefault;

/**
 * OpportunitiesList Shared Slice
 *
 * - **API ID**: `opportunities_list`
 * - **Description**: A section displaying job opportunities in a grid layout with filtering and viewing options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesListSlice = prismic.SharedSlice<
  "opportunities_list",
  OpportunitiesListSliceVariation
>;

/**
 * Item in *OpportunitiesSection → Default → Primary → Job Cards*
 */
export interface OpportunitiesSectionSliceDefaultPrimaryJobCardsItem {
  /**
   * Job Title field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  jobTitle: prismic.KeyTextField;

  /**
   * Job Date field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobDate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  jobDate: prismic.DateField;

  /**
   * Technologies field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Job Description field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobDescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  jobDescription: prismic.RichTextField;
}

/**
 * Primary content in *OpportunitiesSection → Default → Primary*
 */
export interface OpportunitiesSectionSliceDefaultPrimary {
  /**
   * Hero Image field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.heroImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  heroImage: prismic.ImageField<never>;

  /**
   * Section Title field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sectionTitle: prismic.RichTextField;

  /**
   * Job Cards field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  jobCards: prismic.GroupField<
    Simplify<OpportunitiesSectionSliceDefaultPrimaryJobCardsItem>
  >;

  /**
   * CTA Button Text field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.ctaButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ctaButtonText: prismic.KeyTextField;

  /**
   * CTA Button Link field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.ctaButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctaButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for OpportunitiesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of the opportunities section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunitiesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OpportunitiesSection*
 */
type OpportunitiesSectionSliceVariation = OpportunitiesSectionSliceDefault;

/**
 * OpportunitiesSection Shared Slice
 *
 * - **API ID**: `opportunities_section`
 * - **Description**: A section displaying job opportunities with a hero image, title, repeating job cards, and a call-to-action button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesSectionSlice = prismic.SharedSlice<
  "opportunities_section",
  OpportunitiesSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ListeDocument,
      ListeDocumentData,
      ListeDocumentDataSlicesSlice,
      MentionDocument,
      MentionDocumentData,
      MentionDocumentDataSlicesSlice,
      ProfilDocument,
      ProfilDocumentData,
      ProfilDocumentDataSlicesSlice,
      SingleDocument,
      SingleDocumentData,
      SingleDocumentDataSlicesSlice,
      TagDocument,
      TagDocumentData,
      TagDocumentDataSlicesSlice,
      AllDocumentTypes,
      JobBoardSlice,
      JobBoardSliceDefaultPrimaryJobCardsItem,
      JobBoardSliceDefaultPrimary,
      JobBoardSliceVariation,
      JobBoardSliceDefault,
      JobDetailSlice,
      JobDetailSliceDefaultPrimaryTechnologiesItem,
      JobDetailSliceDefaultPrimary,
      JobDetailSliceVariation,
      JobDetailSliceDefault,
      JobListingsSlice,
      JobListingsSliceDefaultPrimaryOfferingsItemsItem,
      JobListingsSliceDefaultPrimaryHistoryItemsItem,
      JobListingsSliceDefaultPrimary,
      JobListingsSliceVariation,
      JobListingsSliceDefault,
      JobPostingSlice,
      JobPostingSliceDefaultPrimaryTechnologiesItem,
      JobPostingSliceDefaultPrimary,
      JobPostingSliceVariation,
      JobPostingSliceDefault,
      LegalTermsSlice,
      LegalTermsSliceDefaultPrimarySectionsItem,
      LegalTermsSliceDefaultPrimary,
      LegalTermsSliceVariation,
      LegalTermsSliceDefault,
      OpportunitiesListSlice,
      OpportunitiesListSliceDefaultPrimaryOpportunitiesItem,
      OpportunitiesListSliceDefaultPrimary,
      OpportunitiesListSliceVariation,
      OpportunitiesListSliceDefault,
      OpportunitiesSectionSlice,
      OpportunitiesSectionSliceDefaultPrimaryJobCardsItem,
      OpportunitiesSectionSliceDefaultPrimary,
      OpportunitiesSectionSliceVariation,
      OpportunitiesSectionSliceDefault,
    };
  }
}
