// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ListeDocumentDataSlicesSlice = JobBoardSlice;

/**
 * Content for liste documents
 */
interface ListeDocumentData {
  /**
   * Slice Zone field in *liste*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ListeDocumentDataSlicesSlice>; /**
   * Meta Title field in *liste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: liste.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *liste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: liste.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *liste*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: liste.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * liste document from Prismic
 *
 * - **API ID**: `liste`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ListeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ListeDocumentData>, "liste", Lang>;

type TagDocumentDataSlicesSlice = OpportunitiesListSlice;

/**
 * Content for tag documents
 */
interface TagDocumentData {
  /**
   * Slice Zone field in *tag*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TagDocumentDataSlicesSlice>; /**
   * Meta Title field in *tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tag.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tag.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *tag*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tag.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TagDocumentData>, "tag", Lang>;

export type AllDocumentTypes = HomeDocument | ListeDocument | TagDocument;

/**
 * Item in *JobBoard → Default → Primary → Job Cards*
 */
export interface JobBoardSliceDefaultPrimaryJobCardsItem {
  /**
   * Job Title field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_title: prismic.RichTextField;

  /**
   * Job Reference field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_reference
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_reference: prismic.KeyTextField;

  /**
   * Technologies field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  technologies: prismic.RichTextField;

  /**
   * Job Description field in *JobBoard → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[].job_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  job_description: prismic.RichTextField;
}

/**
 * Primary content in *JobBoard → Default → Primary*
 */
export interface JobBoardSliceDefaultPrimary {
  /**
   * Title field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Filter Buttons field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.filter_buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  filter_buttons: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Job Cards field in *JobBoard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_board.default.primary.job_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  job_cards: prismic.GroupField<
    Simplify<JobBoardSliceDefaultPrimaryJobCardsItem>
  >;
}

/**
 * Default variation for JobBoard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with job listings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobBoardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JobBoardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JobBoard*
 */
type JobBoardSliceVariation = JobBoardSliceDefault;

/**
 * JobBoard Shared Slice
 *
 * - **API ID**: `job_board`
 * - **Description**: A job listings section with title, filter buttons, and a grid of job cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type JobBoardSlice = prismic.SharedSlice<
  "job_board",
  JobBoardSliceVariation
>;

/**
 * Item in *OpportunitiesList → Default → Primary → Opportunities*
 */
export interface OpportunitiesListSliceDefaultPrimaryOpportunitiesItem {
  /**
   * Job Title field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].jobTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  jobTitle: prismic.RichTextField;

  /**
   * Posting Date field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].postingDate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  postingDate: prismic.DateField;

  /**
   * Technologies field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Techno1, Techno2, Techno3
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Description field in *OpportunitiesList → Default → Primary → Opportunities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *OpportunitiesList → Default → Primary*
 */
export interface OpportunitiesListSliceDefaultPrimary {
  /**
   * Heading field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Techno 1
   * - **API ID Path**: opportunities_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Opportunity Count field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunityCount
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  opportunityCount: prismic.NumberField;

  /**
   * View All Link field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.viewAllLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  viewAllLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Opportunities field in *OpportunitiesList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_list.default.primary.opportunities[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  opportunities: prismic.GroupField<
    Simplify<OpportunitiesListSliceDefaultPrimaryOpportunitiesItem>
  >;
}

/**
 * Default variation for OpportunitiesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunitiesListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OpportunitiesList*
 */
type OpportunitiesListSliceVariation = OpportunitiesListSliceDefault;

/**
 * OpportunitiesList Shared Slice
 *
 * - **API ID**: `opportunities_list`
 * - **Description**: A section displaying job opportunities in a grid layout with filtering and viewing options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesListSlice = prismic.SharedSlice<
  "opportunities_list",
  OpportunitiesListSliceVariation
>;

/**
 * Item in *OpportunitiesSection → Default → Primary → Job Cards*
 */
export interface OpportunitiesSectionSliceDefaultPrimaryJobCardsItem {
  /**
   * Job Title field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  jobTitle: prismic.KeyTextField;

  /**
   * Job Date field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobDate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  jobDate: prismic.DateField;

  /**
   * Technologies field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].technologies
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  technologies: prismic.KeyTextField;

  /**
   * Job Description field in *OpportunitiesSection → Default → Primary → Job Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[].jobDescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  jobDescription: prismic.RichTextField;
}

/**
 * Primary content in *OpportunitiesSection → Default → Primary*
 */
export interface OpportunitiesSectionSliceDefaultPrimary {
  /**
   * Hero Image field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.heroImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  heroImage: prismic.ImageField<never>;

  /**
   * Section Title field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sectionTitle: prismic.RichTextField;

  /**
   * Job Cards field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.jobCards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  jobCards: prismic.GroupField<
    Simplify<OpportunitiesSectionSliceDefaultPrimaryJobCardsItem>
  >;

  /**
   * CTA Button Text field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.ctaButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ctaButtonText: prismic.KeyTextField;

  /**
   * CTA Button Link field in *OpportunitiesSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunities_section.default.primary.ctaButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctaButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for OpportunitiesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of the opportunities section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunitiesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OpportunitiesSection*
 */
type OpportunitiesSectionSliceVariation = OpportunitiesSectionSliceDefault;

/**
 * OpportunitiesSection Shared Slice
 *
 * - **API ID**: `opportunities_section`
 * - **Description**: A section displaying job opportunities with a hero image, title, repeating job cards, and a call-to-action button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OpportunitiesSectionSlice = prismic.SharedSlice<
  "opportunities_section",
  OpportunitiesSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ListeDocument,
      ListeDocumentData,
      ListeDocumentDataSlicesSlice,
      TagDocument,
      TagDocumentData,
      TagDocumentDataSlicesSlice,
      AllDocumentTypes,
      JobBoardSlice,
      JobBoardSliceDefaultPrimaryJobCardsItem,
      JobBoardSliceDefaultPrimary,
      JobBoardSliceVariation,
      JobBoardSliceDefault,
      OpportunitiesListSlice,
      OpportunitiesListSliceDefaultPrimaryOpportunitiesItem,
      OpportunitiesListSliceDefaultPrimary,
      OpportunitiesListSliceVariation,
      OpportunitiesListSliceDefault,
      OpportunitiesSectionSlice,
      OpportunitiesSectionSliceDefaultPrimaryJobCardsItem,
      OpportunitiesSectionSliceDefaultPrimary,
      OpportunitiesSectionSliceVariation,
      OpportunitiesSectionSliceDefault,
    };
  }
}
